debian/theme/dots.png /usr/share/openstack-dashboard-ubuntu-theme/static/dashboard/img
debian/theme/favicon-ubuntu.ico /usr/share/openstack-dashboard-ubuntu-theme/static/dashboard/img
debian/theme/header_stripes.png /usr/share/openstack-dashboard-ubuntu-theme/static/dashboard/img
debian/theme/ubuntu.css /usr/share/openstack-dashboard-ubuntu-theme/static/dashboard/css
debian/theme/ubuntu.png /usr/share/openstack-dashboard-ubuntu-theme/static/dashboard/img
debian/theme/ubuntu_theme.py /etc/openstack-dashboard
